# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b8b11bd491d405575976207531e3ad6f445dd62918cce7c03641c3c528bda5ace6d7831db0e03554de7d4ef67b30745980e3ee52be2b8db6ea1f3ec77045949

test:
  secret_key_base: 2ee386e6e635c46aaede3a03ac9fd3fe00352025d457455cf5ca7cd855fbb0ffc3e5802e39d48fedcf2855dd042ff1811a8db880f5d2a35c43c3d9873dca8cf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
